name: Build and Dockerize

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: demoJavaProject
          push: false
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Tag Docker image
        run: |
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest

