name: Build and Push (Manual Docker Login)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21 for Java compilation
      - name: Set up JDK 21   
        uses: actions/setup-java@v4
        with:
          java-version: "21" 
          distribution: "temurin"

      # Step 3: Extract sanitized repository name
      - name: Extract sanitized repo name
        run: |
          RAW_REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2) 
          SANITIZED_REPO_NAME=$(echo "$RAW_REPO_NAME" | sed 's/-*$//')
          echo "REPO_NAME=$SANITIZED_REPO_NAME" >> $GITHUB_ENV

      # Step 4: Log in to Docker Hub using GitHub Secrets for security
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password:  dckr_pat_pn0g2w2B6tDE3BXWTsnmGhmEhbc

      # Step 5: Build Docker Image from the Dockerfile
      - name: Build Docker Image
        run: |
          docker build -t sanchalkhedkar/newspringboot:latest .  # Build image from the root directory

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push sanchalkhedkar/newspringboot

      # Step 7: Log out from Docker Hub
      - name: Log out from Docker Hub
        run: docker logout
