name: Build and Dockerize

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven Wrapper
        run: |
          cd demoJavaProject
          ls -al
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests
