name: Build and Push (Manual Docker Login)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21   
        uses: actions/setup-java@v4
        with:
          java-version: "21" 
          distribution: "temurin"

    #  - name: Extract sanitized repo name
      #  run: |
        #  RAW_REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2) 
         # SANITIZED_REPO_NAME=$(echo "$RAW_REPO_NAME" | sed 's/-*$//')
          #echo "REPO_NAME=$SANITIZED_REPO_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_pn0g2w2B6tDE3BXWTsnmGhmEhbc
      
      - name: Build Docker Image
        run: |
          docker build -t sanchalkhedkar/newspringboot:latest ./demoJavaProject # Build the image, '.' is important

      - name: Push Docker Image
        run: |
            docker push sanchalkhedkar/newspringboot

      - name: Log out from Docker Hub
        run: docker logout # Log out from Docker Hub
