name: Build and Push (Manual Docker Login)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Extract sanitized repo name
        run: |
          RAW_REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SANITIZED_REPO_NAME=$(echo "$RAW_REPO_NAME" | sed 's/-*$//')
          echo "REPO_NAME=$SANITIZED_REPO_NAME" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sanchalkhedkar
          password: dckr_pat_pn0g2w2B6tDE3BXWTsnmGhmEhbc

      - name: Build Docker Image (from JAR - existing)
        run: |
          docker build -t sanchalkhedkar/newspringboot:latest ./demoJavaProject # Build the image using the Dockerfile in ./demoJavaProject

      # Add the new step here to build directly from source (using the other Dockerfile)
      - name: Build Docker Image (from Source)
        run: |
          docker build -t sanchalkhedkar/newspringboot-source:latest -f ./Dockerfile . # Assuming your source Dockerfile is at the repository root

      - name: Push Docker Image (JAR)
        run: |
          docker push sanchalkhedkar/newspringboot

      # Optionally push the source-built image as well
      - name: Push Docker Image (Source)
        run: |
          docker push sanchalkhedkar/newspringboot-source

      - name: Log out from Docker Hub
        run: docker logout # Log out from Docker Hub
