name: Build and Dockerize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Extract sanitized repo name
        id: vars
        run: |
          RAW_REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          SANITIZED_REPO_NAME=$(echo "$RAW_REPO_NAME" | sed 's/-*$//')
          echo "REPO_NAME=$SANITIZED_REPO_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: demoJavaProject
          push: false
          tags: ${{ github.actor }}/${{ env.REPO_NAME }}:${{ github.sha }}

      - name: Tag Docker image as latest
        run: |
          docker tag ${{ github.actor }}/${{ env.REPO_NAME }}:${{ github.sha }} ${{ github.actor }}/${{ env.REPO_NAME }}:latest
