name: Build and Dockerize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'  # Or your project's Java version
          distribution: 'temurin'

      - name: Build with Maven Wrapper
        run: |
          chmod +x ./mvnw  # Make sure the wrapper is executable
          ./mvnw clean package -DskipTests # Build the JAR

      - name: Build Docker image
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
          docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest

      # Optional: Push to Docker Hub
      #- name: Log in to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Push Docker images
      #  run: |
      #    docker push ${{ github.repository }}:${{ github.sha }}
      #    docker push ${{ github.repository }}:latest
